POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Frank W. Benson",
    "title": "Sunlight",
    "year": 1909,
    "category": "Painting",
    "method": "Oil paint, Canvas",
    "dimensions": "32 x 20",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/sunlight_benson.jpg"
}

###

POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Émile Bernard",
    "title": "Breton Women at a Wall",
    "year": 1892,
    "category": "Painting",
    "method": "Oil paint, Cardboard",
    "dimensions": "32.875 x 45.5",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/breton_women_at_a_wall_emile.jpg"
}

###


POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Isabel Bishop",
    "title": "Tidiying Up",
    "year": 1941,
    "category": "Painting",
    "method": "Oil paint, Masonite",
    "dimensions": "15 x 11.5",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/tidiying_up_isabel.jpg"
}

###

POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Alfred Thompson Bricher",
    "title": "Morning at Grand Manan",
    "year": 1878,
    "category": "Painting",
    "method": "Oil paint, Canvas",
    "dimensions": "25 x 50",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/morning_at_grand_manan_alfred.jpg"
}

###
POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Jean-Baptiste Carpeaux",
    "title": "The Negress",
    "year": 1868,
    "category": "Sculpture",
    "method": "Bronze",
    "dimensions": "22.375",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/the_negress_jean-baptiste.jpg"
}

###
POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Paul Cézanne",
    "title": "House in Provence",
    "year": 1885,
    "category": "Painting",
    "method": "Oil paint, Canvas",
    "dimensions": "25.5 x 32",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/house_in_provence_paul.jpg"
}

###

POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "William Merritt Chase",
    "title": "Dorothy",
    "year": 1902,
    "category": "Painting",
    "method": "Oil paint, Canvas",
    "dimensions": "72 x 36",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/dorothy_william.jpg"
}

###
POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "John Sell Cotman",
    "title": "Blasting St. Vincent's Rock, Clifton",
    "year": 1830,
    "category": "Painting",
    "method": "Watercolor, Gum arabic, Pencil, Paper",
    "dimensions": "13.5 x 22.75",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/blasting_st_vincents_rock_clifton_john.jpg"
}

###
POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Lucas Cranach the Elder",
    "title": "The Crucifixion",
    "year": 1532,
    "category": "Painting",
    "method": "Oil paint, Wood",
    "dimensions": "30 x 21.5",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/the_crucifixion_lucas.jpg"
}

###
POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Aelbert Cuyp",
    "title": "The Valkhof at Nijmegen",
    "year": 1652-4,
    "category": "Painting",
    "method": "Oil paint, Wood",
    "dimensions": "19.25 x 29",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/the_crucifixion_lucas.jpg"
}

###
POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Edgar Degas",
    "title": "Young Woman in Blue",
    "year": 1882,
    "category": "Painting",
    "method": "Pastel, Paper",
    "dimensions": "18.5 x 29",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/young_woman_in_blue_edgar.jpg"
}

###
POST http://localhost:3000/admin/products HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artist": "Émile Bernard",
    "title": "Nus dans un paysage",
    "year": 1890,
    "category": "Painting",
    "method": "Oil paint, Canvas",
    "dimensions": "23.7 x 19.4",
    "collection": "",
    "price": "1",
    "quantity": "1",
    "image": "http://localhost:3000/web/images/product/nus_dans_un_paysage_emil.jpg"
}

###



PUT http://localhost:3000/admin/products/FraSun1 HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "collection": ""
}

###
DELETE  http://localhost:3000/admin/products/FraSun1 HTTP/1.1
content-type: application/json
x-auth: Hola

###
GET  http://localhost:3000/products HTTP/1.1
content-type: application/json

###
GET  http://localhost:3000/products/AlfMor1 HTTP/1.1
content-type: application/json


###

POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 1,
    "artist": "Frank W. Benson",
    "year": 1862,
    "nationality": "American",
    "description":  " American artist from Salem, Massachusetts known for his Realistic portraits, American Impressionist paintings, watercolors and etchings.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###

POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 2,
    "artist": "Émile Bernard",
    "year": 1868,
    "nationality": "French",
    "description":  "French Post-Impressionist painter and writer, who had artistic friendships with Vincent van Gogh, Paul Gauguin and Eugène Boch, and at a later time, Paul Cézanne. Most of his notable work was accomplished at a young age, in the years 1886 through 1897. He is also associated with Cloisonnism and Synthetism, two late 19th-century art movements.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###

POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 3,
    "artist": "Isabel Bishop",
    "year": 1902,
    "nationality": "American",
    "description":  "American painter and graphic artist. Bishop studied under Kenneth Hayes Miller at the Art Students League of New York, where she would later become an instructor. She was most notable for her scenes of everyday life in Manhattan, as a member of the loosely-defined ‘Fourteenth Street School’ of artists, grouped in that precinct.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###
POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 4,
    "artist": "Alfred Thompson Bricher",
    "year": 1837,
    "nationality": "American",
    "description":  "American painter associated with White Mountain art and the Hudson River School.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###
POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 5,
    "artist": "Jean-Baptiste Carpeaux",
    "year": 1827,
    "nationality": "French",
    "description":  "French sculptor and painter during the Second Empire under Napoleon III.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###
POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 6,
    "artist": "Paul Cézanne",
    "year": 1839,
    "nationality": "French",
    "description":  "French Post-Impressionist painter whose work introduced new modes of representation and influenced avant-garde artistic movements of the early 20th century. Cézanne is said to have formed the bridge between late 19th-century Impressionism and early 20th century Cubism.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###
POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 7,
    "artist": "William Merritt Chase",
    "year": 1849,
    "nationality": "American",
    "description": "American painter, known as an exponent of Impressionism and as a teacher. He is also responsible for establishing the Chase School, which later became the Parsons School of Design.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###
POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 8,
    "artist": "John Sell Cotman",
    "year": 1782,
    "nationality": "British",
    "description": "English marine and landscape painter, etcher, illustrator, and a leading member of the Norwich School of painters.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###
POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 9,
    "artist": "Lucas Cranach the Elder",
    "year": 1472,
    "nationality": "German",
    "description": " German Renaissance painter and printmaker in woodcut and engraving. He was court painter to the Electors of Saxony for most of his career, and is known for his portraits, both of German princes and those of the leaders of the Protestant Reformation, whose cause he embraced with enthusiasm. He was a close friend of Martin Luther.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###
POST http://localhost:3000/admin/artists HTTP/1.1
content-type: application/json
x-auth: Hola

{
    "artistNumber": 10,
    "artist": "Edgar Degas",
    "year": 1834,
    "nationality": "French",
    "description": "French Impressionist artist famous for his pastel drawings and oil paintings. Degas also produced bronze sculptures, prints, and drawings. Degas is especially identified with the subject of dance; more than half of his works depict dancers.",
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "pinterest": "pinterest.com"
}

###

###
GET  http://localhost:3000/products HTTP/1.1
content-type: application/json
page: 10

###

GET  http://localhost:3000/artists/artist HTTP/1.1
content-type: application/json

{
    "value": "Frank W. Benson"
}
###

GET  http://localhost:3000/products/artist HTTP/1.1
content-type: application/json
value: Frank W. Benson